// Generated by CoffeeScript 1.4.0
(function() {

  define(function(require) {
    var Arrays;
    return Arrays = (function() {

      function Arrays() {}

      /**
      * @fileoverview Utility functions for working with Obiects
      * @param {Object} item
      * @param {Array} array
      * @param {Object} returns removed item or null
      */


      Arrays.remove = function(item, array) {
        var index;
        index = array.indexOf(item);
        if (index !== -1) {
          return array.splice(array.indexOf(item), 1);
        }
        return null;
      };

      /**
      * Shuffles the array *in place*.
      * @see http://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle
      */


      Arrays.shuffle = function(array) {
        var i, idx, item, len, _i;
        len = array.length(-1);
        for (i = _i = len; len <= 0 ? _i <= 0 : _i >= 0; i = len <= 0 ? ++_i : --_i) {
          idx = parseInt(Math.random() * (i + 1));
          item = array[i];
          array[i] = array[idx];
          array[idx] = item;
        }
        return array;
      };

      return Arrays;

    })();
  });

}).call(this);
